version: "2"

run:
  timeout: 3m
  tests: false

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - errcheck
    - misspell
    - unused
    - goconst

formatters:
  enable:
    - gofumpt

  settings:
    gofumpt:
      extra-rules: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
